#!/bin/bash
#-*- ENCODING: UTF-8 -*-

container=neo4j
container_ports='-p 9000:7687 -p 9090:7474 -p 9990:7473 -p 30:22'
description_ports="
        7687    bolt
        7474    neo4j
        7473    rise
        25      ssh
"
source $(dirname $0)/../cmd-container-template
