version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: wagtail-redis

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
      target: base-develop
    container_name: wagtail-db
    restart: always
    tty: true
    ports:
      - 5432:5432
      - 24:22

  web:
    build:
      context: ./django
      dockerfile: Dockerfile
      target: base-develop
    container_name: wagtail
    restart: always
    tty: true
    depends_on:
      - redis
      - db
      - neo4j
      - vue
    ports:
      - 23:22
      - 80:80
      - 8001:8080
      - 5000:5000
      - 5050:5555
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: wait-for-it db:5432 -- django-migrate
