version: "3.7"

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/database/postgres

services:
  redis:
    image: redis:latest
    container_name: wagtail-redis

  db:
    image: postgres:11
    container_name: wagtail-db
    volumes:
      - postgres:/var/lib/postgresql/data
    tty: true
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: userdb
      POSTGRES_DB: wagtaildb
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    security_opt:
      - seccomp:unconfined

  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
      args:
        AWS_SECRET: ${AWS_SECRET_NUXT}
        AWS_ACCESS: ${AWS_ACCESS_NUXT}
        AWS_REGION: ${AWS_REGION}
    container_name: wagtail-vue
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_NUXT}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_NUXT}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_CLOUDFRONT=${AWS_CLOUDFRONT}
      - BASE_URL=http://0.0.0.0:7000
    volumes:
      - ./vue:/app/vue
      - /app/vue/node_modules
    ports:
      - 80:80
    command: >
      bash -c "npm run serve -- --port 80 --spa"

  web:
    build:
      context: ./django
      dockerfile: Dockerfile
      target: base-develop
      args:
        ANSIBLE_KEY: ${ANSIBLE_KEY}
        AWS_ACCESS: ${AWS_ACCESS}
        AWS_SECRET: ${AWS_SECRET}
        AWS_REGION: ${AWS_REGION}
    container_name: wagtail
    tty: true
    depends_on:
      - redis
      - db
      - vue
    volumes:
      - ./django:/webapps/wagtailblog
      - ./django/ansible:/tmp/ansible
      - ./.env:/webapps/wagtailblog/.env
    ports:
      - 7000:80 # nginx
      - 7001:7001 # ./manage.py shell_plus --notebook
      - 7002:7002 # ./manage.py runserver
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - SECRET_KEY=${SECRET_KEY}
      - ANSIBLE_KEY=${ANSIBLE_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
    command: >
      sh -c "
        cp /root/zappa_settings.json /webapps/wagtailblog/zappa_settings.json &&
        wait-for-it db:5432 --strict --timeout=60 -- django-migrate &&
        poetry lock --no-update &&
        poetry export -n --without-hashes -f requirements.txt -o ./requirements.txt &&
        echo 'set -a; source /webapps/wagtailblog/.env; set +a' >> /opt/venv/bin/postactivate &&
        service supervisor start &&
        supervisorctl reread &&
        supervisorctl update &&
        supervisorctl start all &&
        service ssh start &&
        service nginx start &&
        bash
      "
