version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: wagtail-redis

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
      target: base-develop
    container_name: wagtail-db
    restart: always
    tty: true
    volumes:
      # - postgres:/var/lib/postgresql/11/main  # usar cuando se inicia por primera vez
      - ./data/postgres:/var/lib/postgresql/11/main
    ports:
      - 5432:5432
      - 24:22

  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
      target: base-develop
    container_name: wagtail-vue
    deploy:
      resources:
        limits:
            cpus: '0.50'
            memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    volumes:
      - ./vue/wagtail-vue:/app/vue
      - /app/node_modules
    ports:
      - 80:80

  web:
    build:
      context: ./django
      dockerfile: Dockerfile
      target: base-develop
    container_name: wagtail
    restart: always
    tty: true
    depends_on:
      - redis
      - db
      - vue
    volumes:
      - ./django:/webapps/django
      - ./django/ansible:/tmp/ansible
    ports:
      - 7000:80
      - 7001:8080
      - 7002:5555
      - 7003:7000  # ./manage.py runserver
      - 23:22
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: >
      sh -c "service supervisor start &&
             supervisorctl reread &&
             supervisorctl update &&
             supervisorctl start all &&
             service ssh start &&
             service nginx start &&
             wait-for-it db:5432 --strict --timeout=60 -- django-migrate &&
             /bin/bash"

# usar cuando se inicia por primera vez
#volumes:
#  postgres:
#    driver: local-persist
#    driver_opts:
#      mountpoint: ${PWD}/data/postgres
#  neo4j:
#    driver: local-persist
#    driver_opts:
#      mountpoint: ${PWD}/data/neo4j
