#!/bin/bash
#-*- ENCODING: UTF-8 -*-

container=project
container_ports='-p 23:22 -p 8000:80 -p 5050:5555 -p 8001:8080'
description_ports="
        80      nginx
        5555    flower
        8001    airflow
        23      ssh
"
project=true

source $(pwd $0)/../cmd-container-template