#!/bin/bash
#-*- ENCODING: UTF-8 -*-

container=project
container_ports='-p 23:22 -p 7000:80 -p 7001:8080 -p 7002:5555'
description_ports="
        80      nginx
        5555    flower
        8001    airflow
        23      ssh
"
project=true

source $(dirname $0)/../cmd-container-template