---
group: "{{ vault_group }}"
user: "{{ vault_user }}"
home: "{{ vault_home }}"
path_venv: "/opt/venv"  # Recuerda modificar travis si cambias este valor

# Estas contraseñas deben coincidir con las postgres
database_name: "{{ vault_database_name }}"
postgresql_user: "{{ vault_postgresql_user }}"
postgresql_password: "{{ vault_postgresql_password }}"

# Configuraciones AIRFLOW
host_airflow: http://localhost:8080
web_server_host: 0.0.0.0
web_server_port: 8080
redis: redis://redis:6379
flower_host: 0.0.0.0
flower_port: 5555
queue_names:
  - queue_1
  - queue_2

# ADMIN User django
django_user: "{{ vault_django_user }}"
django_email: "{{ vault_django_email }}"
django_password: "{{ vault_django_password }}"

# SUPERVISOR config
web_socket: tcp://0.0.0.0:8003

# NGINX config
server_name: localhost 127.0.0.1
origin: http://localhost:8003
...
