#!/bin/bash
#-*- ENCODING: UTF-8 -*-

container=postgres
container_ports='-p 5432:5432 -p 24:22'
description_ports="
        5432    postgresql
        24      ssh
"
source $(dirname $0)/../cmd-container-template